# Site settings
title: STAT 545 Course Website
descrp: GLM & CATEGORICAI DATA ANALYSIS
email: yinsen.miao@rice.edu
description: "STAT 545 GLM and CATEGORICAI DATA ANALYSIS course website for Fall 2015"
baseurl: "/stat545"
url: "http://yinsenm.github.io"

# Build settings
markdown: kramdown
permalink: pretty
