# Site settings
title: STAT 545 Course Website
descrp: GLM & CATEGORICAL DATA ANALYSIS
email: yinsen.miao@rice.edu
description: "STAT 545 GLM and CATEGORICAL DATA ANALYSIS course website for Fall 2015"
baseurl: "/stat545"
url: "http://yinsenm.github.io"

paginate:  5

# Build settings
markdown: kramdown
permalink: pretty
